version: "2.4"
services:
  mysql:
    build: mysql-microservice/.
    ports:
      - "6603:3306"
    volumes:
      - ./mysql-microservice/data:/var/lib/mysql
  api:
    build: nodejs-microservice/.
    ports:
      - "3001:3001"
    external_links:
      - mysql:db
    env_file: nodejs-microservice/.env
    depends_on: 
      - mysql
